---
- name: Install base OS dependencies
  package: 
    name:
      - git
      - curl
      - unzip
      - astral-uv 
      - podman
      - python3
      - python3-pip 
    state: present

# -- Python dependencies -- 
- name: Install python dependencies
  pip: 
    name: 
      - boto3
      - requests
      - argparse
      - pathlib
      - aiohttp
      - asyncio
      - urllib
      - pathlib
      - ramalama 
    executable: pip3 
 
 
