name: Destroy ECR repo
run-name: ${{ github.actor }} is destroying the ECR repo
on:
  #   push:
  #     branches:
  #       - main
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  destroy-ecr-repo:
    name: Destroy ECR repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::620339869704:role/gcp-github-oidc-trust-policy
          aws-region: us-east-1

      - name: Destroy repo
        shell: bash
        run: |
          aws ecr delete-repository \
          --repository-name gcp_ecr_repository \
          --force \
          --region us-east-1
