name: Destroy RAG stack
run-name: ${{ github.actor }} is destroying the RAG stack
on:
  #   push:
  #     branches:
  #       - main
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  generate-rag:
    name: Destroy RAG stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::620339869704:role/gcp-github-oidc-trust-policy
          aws-region: us-east-1

      - name: Install dependencies
        shell: bash
        run: |
          cd rag-cdk
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: CDK Deploy
        shell: bash
        run: |
          cd rag-cdk
          source .venv/bin/activate
          cdk destroy --force
