name: Run Ansible on ECS
run-name: ${{ github.actor }} is running Ansible on ECS
on:
  #   push:
  #     branches:
  #       - main
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  run-ansible-on-ecs:
    name: Run Ansible on ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::620339869704:role/gcp-github-oidc-trust-policy
          aws-region: us-east-1

      - name: start up ECS with Fargate(?)
        shell: bash
        run: |
        aws ec2 
